Repository golagola2020/hango-arduino, pull requests merged in 2020-10, with the labels that each got.

#5 [docs] MIT 라이선스 적용
  LICENSE
Labels: 라이센스, 문서화, 아두이노

#7 [arduino/refactoring] rx-tx 방향 변경 완료 & 라즈베리파이 테스트 완료
  arduino/capacitive/capacitive.ino
  arduino/capacitive/function.ino
  arduino/pushButton/pushButton.ino
  arduino/switchButton/pushButton.ino
Labels: 기능 개선, 아두이노

#13 [arduino/readme] 행고 아두이노 메인페이지 리드미 수정 - v2.0배포시 링크 수정 필요
  README.md
  arduino/README.md
  arduino/capacitive/README.md
  arduino/pushButton/README.md
Labels: 문서화, 아두이노

#17 [arduino/readme] 메인 readme.md 수정
  README.md
Labels: 문서화

#18 [arduino/duplicate] v1.2.0 중복센싱 방지 완료
  arduino/capacitive/capacitive.ino
  arduino/captest/captest.ino
Labels: 기능 개선, 아두이노

#25 [arduino/libraries] Char2Int 라이브러리 생성 및 capacitive.ino에 적용 & 주석 추가
  arduino/capacitive/capacitive.ino
  arduino/capacitive/function.ino
  arduino/libraries/Char2Int/Char2Int.cpp
  arduino/libraries/Char2Int/Char2Int.h
  arduino/pushButton/pushButton.ino
Labels: 기능 개선, 아두이노

#28 [docs] v1.2.1 문서작업 완료
  CONTRIBUTING.md
  README.md
  arduino/README.md
  arduino/capacitive/README.md
  arduino/captest/captest.ino
Labels: 문서화, 아두이노

#30 [arduino/tag] v1.2.1 배포 완료
  CONTRIBUTING.md
  README.md
  arduino/README.md
  arduino/capacitive/README.md
  arduino/capacitive/capacitive.ino
  arduino/capacitive/function.ino
  arduino/captest/captest.ino
  arduino/libraries/Char2Int/Char2Int.cpp
  arduino/libraries/Char2Int/Char2Int.h
  arduino/pushButton/pushButton.ino
Labels: 배포, 아두이노

#32 [arduino/license] 코드에 MIT 라이센스 명시
  arduino/capacitive/capacitive.ino
  arduino/captest/captest.ino
  arduino/libraries/Char2Int/Char2Int.cpp
  arduino/libraries/Char2Int/Char2Int.h
  arduino/pushButton/pushButton.ino
Labels: 라이센스, 아두이노

#41 [arduino/readme] readme 변경
  README.md
  arduino/capacitive/README.md
Labels: 문서화, 아두이노

#42 [arduino/readme] v1.2.3 readme완성
  README.md
Labels: 문서화, 아두이노
